### PR TITLE
go-soql: Add Date type

### LINKED ISSUE #33: Add support for SOQL Date type?
Hey, first off - just wanted to say that this package is super useful!

I was wondering if it would be possible to add support for a Date type. We're running into this issue where generated queries end up being invalid due to a dateTime string being compared with a date field...

I've taken a stab at this, however haven't implemented the JSON/YAML marshaler/unmarshaler interfaces - what do you think?

Thank you!

### PR DESCRIPTION
**Pull request by mskwon**
resolves #33

### CODE REVIEW

**Comment by atulkc** [comment]
@mskwon Thanks for submitting this PR. However, I think introducing a custom type specifically for only this library will not play well with other tag libraries like `json` and `yaml`. Also, all that is being done as part of this new type is use different parsing format. Here's my proposal to keep it generic and make it extensible in future:

What you really want is the way to declaratively specify date format. I think we should introduce a new optional parameter named `format` that can be added to field of type `time.Time` and use that to specify the right date time format. We can default to existing `DateTimeFormat` if none is provided. We will also need to make sure that this parameter is only added for `time.Time` fields. So the tags should look like this:

```
type QueryCriteriaWithPtrDateTimeType struct {
        // Makes CreatedDate to be parsed in DateFormat
	CreatedDate  *time.Time `soql:"equalsOperator,fieldName=CreatedDate,format=DateFormat"`
        // ResolvedDate will be parsed in default DateTimeFormat
	ResolvedDate *time.Time `soql:"equalsOperator,fieldName=ResolvedDate"`
}
```
This allows us to use standard go data types and allow users to control the format. We can add support for different formats later by adding constants like `DateFormat`, `DateTimeFormat`...etc.

Thoughts?

**Comment by atulkc** [comment]
We will have to change the function signature in `clauseBuilderMap` to take a `map[string]string` to represent any additional parameters. All the functions need to be updated to take this map and use it wherever applicable (in this case when formatting time field).

```
var clauseBuilderMap = map[string]func(v interface{}, fieldName string, map[string]string) (string, error){
```

In `func marshalWhereClause` create a new map with all parameters name value pairs. Introduce a new function
```
func getTagParameterMap(clauseTag string) map[string]string {
// Here do same thing as getTagValue function but accumulate all parameters with `=` in a map with left hand as key and right hand as value
}
```
Invoke this new function in `marshalWhereClause` and then use the map returned by this map in invoking the function you look up from `clauseBuilderMap`

**Comment by mskwon** [comment]
Got it, how about this?

**Review by atulkc — COMMENTED** [review]
This change looks good. Couple of things:
1. Add a test for `*time.Time` as well so that we have coverage for pointy and non-pointy data types.
2. Please sign the CLA agreement so we can merge this PR.

**Review by atulkc — APPROVED** [review]
LGTM and sorry for the delay

**Pull request merged**
